name: SimpleFactions
version: 1.0.0
main: com.convariance.sf.SimpleFactionsPlugin
api-version: "1.21"

author: Convariance

commands:
  faction:
    description: Factions command
    usage: /faction help
    aliases: [f, fac]

permissions:
  simplefactions.admin:
    description: Admin permissions for SimpleFactions
    default: op
